name: 'Hello World Docker Action'
description: 'Says hello to the person you specify'
author: 'Your Name'
inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'World'
outputs:
  message:
    description: 'The greeting message'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
